### ISSUE TITLE
Add option to use sandbox in GraphQL playground

### ISSUE THREAD

**Issue by thgh** [nckhell/awell-developers#58]

**Comment by nckhell** [comment]
Hi @thgh,

Anything we could help you with? You should be able to use the Playground to interact with the Sandbox environment. All you need is an API key. Always happy to get in touch to see how we could help each other.

Cheers,
Nick

**Comment by thgh** [comment]
Oh sorry, looks like I put the api key in the query variables instead of the request headers tab.
